/** One layer catalog + six scenarios. Architecture draws this; Learn keeps the essays. */

const CS = "https://cs.android.com/android/platform/superproject/+/android-latest-release:";

export const LAYERS = [
  {
    id: "app",
    n: 1,
    process: "app",
    name: "App / client",
    color: "#00E5FF",
    who: "A process that wants sound. Not a second audio OS.",
    beginner: "The musician. AudioTrack, MediaPlayer, AAudio — they write samples or encoded frames and attach a usage badge.",
    engineer: "The app Binders to AudioFlinger for createTrack / IAudioTrack and writes PCM (or encoded frames) into shared memory. It does not call AudioPolicyManager itself. Focus and volume go to AudioService (and CarAudioService on AAOS).",
    architect: "Wrong usage is the most common ‘routing’ bug. play() ≠ acoustic energy. Routing happens because Flinger called getOutputForAttr during createTrack — before play().",
    files: [
      { name: "AudioTrack.java", url: `${CS}frameworks/base/media/java/android/media/AudioTrack.java` },
      { name: "AudioTrack.cpp", url: `${CS}frameworks/av/media/libaudioclient/AudioTrack.cpp` },
    ],
    fails: ["play() returned, no Flinger track", "USAGE_MEDIA on a ringtone", "Offload expected, landed on MixerThread"],
    cmd: "adb logcat -s AudioTrack AAudio",
  },
  {
    id: "policy",
    n: 3,
    process: "audioserver",
    name: "AudioPolicy",
    color: "#FFB300",
    who: "The program director. Peer of Flinger in the same audioserver process, not a layer under it.",
    beginner: "Decides where a stream should go and who may be loud. Does not mix PCM.",
    engineer: "Flinger calls AudioSystem.getOutputForAttr → IAudioPolicyService. Mix-port patches are created via AudioPolicyClient, which asks AudioFlinger — Policy does not burst PCM to the HAL.",
    architect: "A live patch is not ‘possible devices.’ On AIDL, APM gets IModule/IConfig topology through AudioFlinger/libaudiohal at startup; it has no HAL binder of its own. Device AVAILABLE ≠ Flinger moved.",
    files: [
      { name: "AudioPolicyService.cpp", url: `${CS}frameworks/av/services/audiopolicy/service/AudioPolicyService.cpp` },
      { name: "AudioPolicyManager.cpp", url: `${CS}frameworks/av/services/audiopolicy/managerdefault/AudioPolicyManager.cpp` },
    ],
    fails: ["Wrong device / bus address", "Profile lie → HAL EINVAL", "AVAILABLE on a sink Flinger left"],
    cmd: "adb shell dumpsys media.audio_policy",
  },
  {
    id: "svc",
    n: 2,
    process: "system_server",
    name: "AudioService / Car",
    color: "#C084FC",
    who: "system_server. AudioService always. CarAudioService only on AAOS. Never in the PCM path.",
    beginner: "The usher: focus, volume keys, devices. In a car, also the building manager (zones and buses).",
    engineer: "AudioService: focus, volume UI, setDevice. CarAudioService: dynamic mixes, per-zone focus, volume groups, car_audio_configuration.xml v4. It programs Policy; Flinger still mixes.",
    architect: "Two contexts on one bus ⇒ the DSP sees one PCM; hardware duck is impossible. Fade XML is not a bus mute. CarAudioService is not a hop on the sample path.",
    files: [
      { name: "AudioService.java", url: `${CS}frameworks/base/services/core/java/com/android/server/audio/AudioService.java` },
      { name: "CarAudioService.java", url: `${CS}packages/services/Car/service/src/com/android/car/audio/CarAudioService.java` },
    ],
    fails: ["Focus ignored by a rude app", "Typo in bus address, silent fallback", "Shared BUS00_MEDIA, no HW duck"],
    cmd: "adb shell dumpsys audio ; adb shell dumpsys car_service --services CarAudioService",
  },
  {
    id: "flinger",
    n: 4,
    process: "audioserver",
    name: "AudioFlinger",
    color: "#38BDF8",
    who: "The mixing console and clock. Executes; does not invent cabin routes.",
    beginner: "Wakes on a period, mixes (or not), hands bytes to the HAL.",
    engineer: "PlaybackThread family: MixerThread (+ FastMixer helper), DirectOutputThread, OffloadThread, DuplicatingThread, Spatializer/BitPerfect/MMAP. Direct/Offload skip the mixer, not Flinger. Dump twice for motion.",
    architect: "STANDBY means the output is idle (stream open; the vendor may have released the PCM). Frozen frames with State=ACTIVE is not an XRUN. Work > period_ms ⇒ you will glitch.",
    files: [
      { name: "AudioFlinger.cpp", url: `${CS}frameworks/av/services/audioflinger/AudioFlinger.cpp` },
      { name: "Threads.cpp", url: `${CS}frameworks/av/services/audioflinger/Threads.cpp` },
    ],
    fails: ["STANDBY through a one-shot chime", "Still bursting to a dead A2DP thread", "XRUN / empty mix"],
    cmd: "adb shell dumpsys media.audio_flinger",
  },
  {
    id: "hal",
    n: 5,
    process: "vendor",
    name: "Audio HAL",
    color: "#00E676",
    who: "Vendor contract. Android 15: IModule + StreamDescriptor, not HIDL write().",
    beginner: "The customs border between Android and the board.",
    engineer: "openOutputStream (when an output opens), setAudioPatch, Command.start/burst/standby on audio.fmq. HAL must drain the whole FMQ. Classify AIDL vs HIDL before naming methods.",
    architect: "libaudiohal hides IPC; bugs still live in the vendor service. libaudiohal reads IConfig and IModule ports for APM. Policy changes ports/patches through AudioFlinger; Flinger uses StreamDescriptor for I/O. Those are different HAL conversations.",
    files: [
      { name: "IModule.aidl", url: `${CS}hardware/interfaces/audio/aidl/android/hardware/audio/core/IModule.aidl` },
    ],
    fails: ["burst xrunFrames climbing", "Stream ERROR / STANDBY", "open EINVAL — format/slot lie"],
    cmd: "adb shell lshal | grep audio",
  },
  {
    id: "alsa",
    n: 6,
    process: "kernel",
    name: "ALSA / ASoC",
    color: "#FB7185",
    who: "Kernel PCM + the factory floor plan (DAI, DMA, clocks).",
    beginner: "The wheel that turns numbers into a serial pin wiggle.",
    engineer: "TinyALSA pcm_open/write. FE PCM vs BE DAI. Period × count is the ring. RUNNING + zeros is not an XRUN.",
    architect: "hw_ptr stuck + PCM RUNNING ⇒ clocks/DAI/DMA, not Policy. Slot map ≠ car XML.",
    files: [
      { name: "tinyalsa", url: `${CS}external/tinyalsa/` },
    ],
    fails: ["open EINVAL / wrong card,device", "XRUN", "RUNNING, hw_ptr frozen"],
    cmd: "adb shell cat /proc/asound/pcm",
  },
  {
    id: "hw",
    n: 7,
    process: "silicon",
    name: "DSP / codec / amp",
    color: "#FF9100",
    who: "Where voltage actually appears. Vendor graphs live here.",
    beginner: "The last valves: DSP, DAC, amplifier enable, speaker.",
    engineer: "DAPM must complete. Amp EN is independent of PCM RUNNING. Qualcomm: ACDB/PAL/AFE are vendor, not AOSP.",
    architect: "Do not invent module IDs, ACDB keys, or PCM device numbers. Ask the BSP. Digital alive + analog off is the classic mute.",
    files: [],
    fails: ["Graph not built / default mute", "Amp EN never asserted", "Wrong TDM slot at the amp"],
    cmd: "tinymix / vendor logs — ask the BSP",
    vendor: true,
  },
];

export const SCENARIOS = [
  {
    id: "media",
    name: "Phone media",
    blurb: "One AudioTrack. createTrack → Policy. PCM only through Flinger.",
    lede: "The app Binders to Flinger for the track and to AudioService for focus. Flinger asks Policy getOutputForAttr. PCM never visits Policy or AudioService. CarAudioService is absent.",
    product: "Phone · AOSP",
    hot: ["app", "svc", "policy", "flinger", "hal", "alsa", "hw"],
    cold: [],
    err: {},
    sinks: { a: { label: "SPEAKER", state: "hot", via: "alsa" }, b: { label: "A2DP", state: "off" } },
    live: {
      control: ["app-svc", "svc-policy", "peer"],
      data: ["app-flinger", "flinger-hal", "hal-alsa", "alsa-a"],
      capture: [],
    },
    sequence: [
      "App AudioTrack.Builder → JNI native_setup (app process)",
      "Binder IAudioFlinger.createTrack — AudioFlinger.cpp, not IAudioPolicyService",
      "Flinger → AudioSystem.getOutputForAttr → AudioPolicyService → SPEAKER / MixerThread",
      "Focus is separate: AudioManager.requestAudioFocus → AudioService → MediaFocusControl (no PCM)",
      "play() → Track::start; if thread STANDBY, next write sends Command.start/burst on the already open HAL stream",
      "App write → mix → Command.burst → TinyALSA → PCM RUNNING → DAC → amp",
    ],
    labels: {
      app: "AudioTrack · USAGE_MEDIA",
      svc: "AudioService · focus / volume",
      policy: "getOutputForAttr → SPEAKER",
      flinger: "MixerThread 48 kHz",
      hal: "IModule/default · burst PCM",
      alsa: "FE PCM RUNNING",
      hw: "Codec + amp + speaker",
    },
    dump: "dumpsys media.audio_flinger  →  MixerThread SPEAKER  48 kHz  standby no",
  },
  {
    id: "navduck",
    name: "AAOS nav + media",
    blurb: "Two outputs. Two HAL streams. Not one mix split at the amp.",
    lede: "CarAudioService already registered two policy mixes. Each createTrack hits a different output. Two MixerThreads, two StreamDescriptors, two FE PCMs. Hardware duck is possible because the DSP never saw one combined PCM.",
    product: "AAOS · two buses",
    hot: ["app", "svc", "policy", "flinger", "hal", "alsa", "hw"],
    cold: [],
    err: {},
    sinks: { a: { label: "BUS_MEDIA", state: "hot", via: "hal" }, b: { label: "BUS_NAV", state: "hot", via: "hal" } },
    live: {
      control: ["app-svc", "svc-policy", "peer"],
      data: ["app-flinger", "flinger-hal", "hal-a", "hal-b"],
      capture: [],
    },
    sequence: [
      "Boot: CarAudioDynamicRouting builds AudioMix per bus; AudioPolicy.Builder.addMix; registerAudioPolicy",
      "Each app: IAudioFlinger.createTrack (same as phone)",
      "Each getOutputForAttr matches a dynamic mix → BUS_MEDIA vs BUS_NAV (two outputs)",
      "Focus: AudioService → CarAudioFocus (registered policy listener), not getOutputForAttr",
      "Two MixerThreads, two StreamDescriptors, two FE PCMs — DSP can HW-duck",
      "Patches that open those outputs go Policy → AudioPolicyClient → Flinger → HAL, not Policy bursting PCM",
    ],
    labels: {
      app: "MEDIA track + NAV track",
      svc: "CarAudioService mixes + CarAudioFocus",
      policy: "two mixes, two patches",
      flinger: "two MixerThreads — not one mix",
      hal: "two streams on IModule (two descriptors)",
      alsa: "two FE PCMs — not a shared mix",
      hw: "two devices / two amps — HW duck possible",
    },
    dump: "dumpsys media.audio_policy  →  mix BUS00_MEDIA + mix BUS01_NAV  (two outputs)",
  },
  {
    id: "carplay",
    name: "CarPlay duplex",
    blurb: "Playback down the stack. Capture back up. ECNR is not Flinger.",
    lede: "Projection still uses Policy + Flinger. Playback is App→Flinger→HAL→cabin. Capture is mic→HAL→RecordThread→App — the opposite direction. Echo cancellation is DSP/vendor, not a Flinger mix. If createRecord fails, output can still look healthy.",
    product: "AAOS · projection",
    hot: ["app", "svc", "policy", "flinger", "hal", "alsa", "hw"],
    cold: [],
    err: {},
    sinks: { a: { label: "CABIN OUT", state: "hot", via: "alsa" }, b: { label: "MIC IN", state: "hot", via: "capture" } },
    live: {
      control: ["app-svc", "svc-policy", "peer"],
      data: ["app-flinger", "flinger-hal", "hal-alsa", "alsa-a"],
      capture: ["cap-b-hal", "cap-hal-flinger", "cap-flinger-app"],
    },
    sequence: [
      "AAudio output: IAudioFlinger.createTrack → getOutputForAttr → PlaybackThread → HAL out → cabin",
      "AAudio input: IAudioFlinger.createRecord → AudioSystem.getInputForAttr → RecordThread",
      "Capture data runs opposite: mic ADC → DAI → capture PCM → HAL in → RecordThread → app",
      "Focus/zone: AudioManager → AudioService / CarAudioService (system_server)",
      "ECNR / AEC is DSP or projection — not a Flinger mix of play+record",
      "If createRecord fails/retries, playback can still dump ACTIVE",
    ],
    labels: {
      app: "AAudio out + in",
      svc: "zone / focus for projection",
      policy: "getOutputForAttr + getInputForAttr",
      flinger: "PlaybackThread + RecordThread",
      hal: "output stream + input stream",
      alsa: "play PCM + capture PCM",
      hw: "amp out + mic (ECNR is vendor/DSP)",
    },
    dump: "dumpsys media.audio_flinger  →  PlaybackThread ACTIVE  and  RecordThread ACTIVE",
  },
  {
    id: "chime",
    name: "Chime on cold output",
    blurb: "Route is right. Output is STANDBY. WAV can finish first.",
    lede: "createTrack and getOutputForAttr succeeded. The PlaybackThread is in STANDBY (stream open, vendor HAL may have released PCM/graph). Standby exit must restart PCM/graph, clocks, amp. If that is longer than the WAV, the cabin never hears it. PCM is not flowing yet — so no data packets.",
    product: "AAOS · power",
    hot: ["app", "svc", "policy", "flinger"],
    cold: ["alsa"],
    err: {
      flinger: "STANDBY: stream idle; standby exit longer than the one-shot",
      hal: "stream not ACTIVE before the WAV ended",
      hw: "amp EN still down",
    },
    sinks: { a: { label: "CHIME BUS", state: "err" }, b: { label: "MEDIA BUS", state: "cold" } },
    live: {
      control: ["app-svc", "svc-policy", "peer"],
      data: [],
      capture: [],
    },
    sequence: [
      "App plays a short WAV / sonification (USAGE_ASSISTANCE_SONIFICATION or similar)",
      "createTrack → getOutputForAttr succeeds — Policy already chose the bus",
      "PlaybackThread is STANDBY: idle sent Command.standby (stream still open, no Command.burst yet)",
      "Standby exit: Command.start, vendor PCM/graph restart, clocks, amp unmute",
      "If bring-up > WAV length, dump still shows standby; speaker never moved",
      "Debug standby/power, not a wrong bus address",
    ],
    labels: {
      app: "short WAV / sonification",
      svc: "CarAudioService context OK",
      policy: "route OK — not the bug",
      flinger: "thread STANDBY — no burst yet",
      hal: "not ACTIVE in time",
      alsa: "not RUNNING yet",
      hw: "rails / amp still down",
    },
    dump: "dumpsys media.audio_flinger  →  standby yes   (dump twice after play — still yes)",
  },
  {
    id: "bt",
    name: "BT A2DP split-brain",
    blurb: "A2DP is not TinyALSA. Frames can increment into a dead headset.",
    lede: "A2DP I/O is Flinger → Bluetooth audio HAL / IModule bluetooth — not the cabin ALSA PCM. Policy may still list A2DP AVAILABLE. Flinger’s thread still bursts. Cabin speaker is cold. Silence in the room, frames++ on a corpse.",
    product: "Phone or car · BT",
    hot: ["app", "svc", "policy", "flinger"],
    cold: ["alsa"],
    err: {
      policy: "A2DP still AVAILABLE after the sink died",
      flinger: "thread still A2DP; frames increment into nowhere",
      hal: "bluetooth HAL / dead ACL transport",
      hw: "headset gone — not the cabin speaker",
    },
    sinks: { a: { label: "SPEAKER", state: "cold" }, b: { label: "A2DP (dead)", state: "err", via: "hal" } },
    live: {
      control: ["app-svc", "svc-policy", "peer"],
      data: ["app-flinger", "flinger-hal", "hal-b"],
      capture: [],
    },
    sequence: [
      "createTrack → getOutputForAttr selected A2DP while the headset was connected",
      "PlaybackThread is the BT output (IModule bluetooth / BT HAL), not speaker TinyALSA",
      "App writes; Flinger Command.burst (or BT writes) to the bluetooth HAL",
      "Disconnect: AudioService should setDeviceConnectionState → Policy; this can lag",
      "Policy dump can still show A2DP AVAILABLE; Flinger frames still ++ into a dead transport",
      "Cabin SPEAKER MixerThread is idle. Not a volume-group bug",
    ],
    labels: {
      app: "still writing MEDIA",
      svc: "AudioService device callback lag",
      policy: "A2DP AVAILABLE — stale",
      flinger: "PlaybackThread still A2DP",
      hal: "IModule bluetooth / BT HAL",
      alsa: "cabin PCM not in this path",
      hw: "no headset; speaker unused",
    },
    dump: "policy: A2DP AVAILABLE    flinger: A2DP thread frames++    speaker: standby    cabin: silence",
  },
  {
    id: "qcom",
    name: "Vendor DSP / ACDB",
    blurb: "AOSP path green. Analog mute in a vendor graph.",
    lede: "MixerThread ACTIVE and TinyALSA RUNNING only prove the AOSP side. On a Qualcomm-like product the HAL hands a use-case to PAL/ACDB/ADSP. A missing calibration entry can mute AFE while Flinger looks healthy. Do not invent module IDs.",
    product: "Qualcomm-like · vendor",
    hot: ["app", "svc", "policy", "flinger", "hal", "alsa"],
    cold: [],
    err: {
      hw: "Graph not built / default mute / AFE not started — vendor, not AOSP",
    },
    sinks: { a: { label: "AFE / codec", state: "err", via: "alsa" }, b: { label: "SPEAKER", state: "cold" } },
    live: {
      control: ["app-svc", "svc-policy", "peer"],
      data: ["app-flinger", "flinger-hal", "hal-alsa", "alsa-a"],
      capture: [],
    },
    sequence: [
      "Same AOSP createTrack → getOutputForAttr → MixerThread as phone media",
      "Command.burst can succeed; FE PCM may be RUNNING",
      "Vendor HAL maps the stream to a PAL use-case; AGM builds the DSP graph; ACDB is calibration — none of these are AOSP objects",
      "Missing calibration tuple → AFE/DAC mute while Flinger looks healthy",
      "Last-known-good is HAL/ALSA; the break is vendor",
      "Do not invent PAL module IDs, ACDB names, or PCM device numbers",
    ],
    labels: {
      app: "MEDIA PCM looks fine",
      svc: "AudioService — not the mute",
      policy: "device matches what Policy knows",
      flinger: "MixerThread ACTIVE, frames move",
      hal: "burst OK — still not analog",
      alsa: "RUNNING ≠ speaker",
      hw: "PAL / AGM / ACDB / AFE — BSP owns names",
    },
    dump: "Flinger ACTIVE + PCM RUNNING  ≠  speaker. Need vendor graph logs.",
  },
];

export function getLayer(id) {
  return LAYERS.find((l) => l.id === id) || LAYERS[0];
}

export function getScenario(id) {
  return SCENARIOS.find((s) => s.id === id) || SCENARIOS[0];
}
