/** Glossary terms. compareId must match a key in comparisons.js or be omitted. */

export const TERMS = [
  { id: "aidl", name: "AIDL Audio HAL", cat: "HAL", layer: "HAL",
    short: "android.hardware.audio.core on Android 15+.",
    catch: "Not HIDL @7.1.",
    beginner: "The current vendor contract Android uses to talk to audio hardware.",
    engineer: "IModule + IConfig + StreamDescriptor.",
    architect: "New HAL APIs after Android 14 are AIDL-only.",
    compareId: "hidl-aidl" },
  { id: "imodule", name: "IModule", cat: "HAL", layer: "HAL",
    short: "AIDL Core HAL entry (replaces HIDL IDevice).",
    catch: "Instances: default, bluetooth, r_submix.",
    beginner: "The HAL box Android opens.",
    engineer: "getAudioPorts, openOutputStream, setAudioPatch.",
    architect: "Registers with ServiceManager; no IDevicesFactory.",
    compareId: "hidl-aidl" },
  { id: "iconfig", name: "IConfig", cat: "HAL", layer: "HAL",
    short: "System-wide engine/surround config served by the HAL.",
    catch: "May convert leftover XML internally.",
    beginner: "The HAL's answer to what the product can do.",
    engineer: "getEngineConfig, getSurroundSoundConfig.",
    architect: "APM reads the API, not a file it owns." },
  { id: "streamdesc", name: "StreamDescriptor", cat: "HAL", layer: "HAL",
    short: "FMQ command/reply/audio plus the HAL stream state machine.",
    catch: "burst is the I/O, not HIDL write.",
    beginner: "Three mailboxes: commands, answers, samples.",
    engineer: "STANDBY → IDLE → ACTIVE → PAUSED → DRAINING → ERROR.",
    architect: "HAL must drain the whole audio FMQ on burst.",
    compareId: "hidl-aidl" },
  { id: "burst", name: "burst", cat: "HAL", layer: "HAL",
    short: "AIDL I/O command against audio.fmq.",
    catch: "Not write(); HAL reads all FMQ bytes.",
    beginner: "A timed “take these samples now.”",
    engineer: "Reply has fmqByteCount, xrunFrames, state.",
    architect: "Needs a high-priority HAL thread.",
    compareId: "hidl-aidl" },
  { id: "audioflinger", name: "AudioFlinger", cat: "API", layer: "Flinger",
    short: "Native mixer/IO server in audioserver.",
    catch: "Executes; does not invent cabin routes.",
    beginner: "The mixing console.",
    engineer: "Threads, tracks, standby, HAL burst.",
    architect: "Dump twice. Frozen frames mean no motion.",
    compareId: "policy-flinger" },
  { id: "audiopolicy", name: "AudioPolicy", cat: "API", layer: "Policy",
    short: "Native decision engine in audioserver.",
    catch: "Does not mix PCM.",
    beginner: "The program director.",
    engineer: "getOutputForAttr, patches, mixes.",
    architect: "Peer of Flinger, not under it.",
    compareId: "policy-flinger" },
  { id: "audiotrack", name: "AudioTrack", cat: "API", layer: "App",
    short: "App PCM playback client.",
    catch: "Construction is already a routing event.",
    beginner: "The object you write samples to.",
    engineer: "play / write / session.",
    architect: "Almost every player ends here.",
    compareId: "track-player" },
  { id: "mediaplayer", name: "MediaPlayer", cat: "API", layer: "App",
    short: "File/URL player that ends in a decoder plus AudioTrack.",
    catch: "Not a second audio system.",
    beginner: "Plays files and streams.",
    engineer: "Prepare/start; sink is a track.",
    architect: "Offload still lands in Flinger as a different thread type.",
    compareId: "track-player" },
  { id: "audioattributes", name: "AudioAttributes", cat: "Focus", layer: "App",
    short: "Meaning of a stream: usage, content type, flags, tags.",
    catch: "Usage is the primary routing/focus key.",
    beginner: "The badge: why this sound exists.",
    engineer: "Maps to a strategy or CarAudioContext.",
    architect: "Wrong usage is the most common AAOS “routing” bug.",
    compareId: "usage-attributes" },
  { id: "usage", name: "Usage", cat: "Focus", layer: "App",
    short: "Why the app plays (MEDIA, RINGTONE, ASSISTANT…).",
    catch: "Not a device.",
    beginner: "The job title on the badge.",
    engineer: "USAGE_* constants.",
    architect: "Ring as MEDIA will not evict assistant.",
    compareId: "usage-attributes" },
  { id: "focus", name: "Focus", cat: "Focus", layer: "App",
    short: "Prominence protocol.",
    catch: "Not a route. System-enforced on phones since Android 12; cooperative before.",
    beginner: "Right-of-way at the intersection.",
    engineer: "GAIN / TRANSIENT / MAY_DUCK; exclusive / reject / concurrent.",
    architect: "An app can ignore LOSS — enforce with mute or fade.",
    compareId: "focus-routing" },
  { id: "routing", name: "Routing", cat: "API", layer: "Policy",
    short: "Choosing the device or bus PCM will use.",
    catch: "Not the same as focus.",
    beginner: "Which cable the sound takes.",
    engineer: "Ports, profiles, patches, dynamic mixes.",
    architect: "On Android 15 topology comes from IModule/IConfig.",
    compareId: "focus-routing" },
  { id: "caraudioservice", name: "CarAudioService", cat: "AAOS", layer: "AAOS",
    short: "AAOS orchestrator of mixes, zones, focus, groups.",
    catch: "Does not replace Flinger.",
    beginner: "The building manager for the car.",
    engineer: "Dynamic mixes, CarAudioFocus, volume groups.",
    architect: "audioUseDynamicRouting is the master switch." },
  { id: "caraudiocontext", name: "CarAudioContext", cat: "AAOS", layer: "AAOS",
    short: "Group of usages for car routing, focus, and volume.",
    catch: "MUSIC includes UNKNOWN and GAME.",
    beginner: "Music vs nav vs call buckets.",
    engineer: "Maps to a bus address in XML v4.",
    architect: "Every context must be assigned in every zone config." },
  { id: "audiozone", name: "Audio zone", cat: "AAOS", layer: "AAOS",
    short: "Independent audio universe (focus, route, volume).",
    catch: "Not the same as occupant zone.",
    beginner: "A room's sound system.",
    engineer: "audioZoneId, zoneConfigs.",
    architect: "Primary zone has one config (Android 14+).",
    compareId: "zone-occupant" },
  { id: "occupantzone", name: "Occupant zone", cat: "AAOS", layer: "AAOS",
    short: "Seat + displays + user.",
    catch: "One-to-one with an audio zone when mapped.",
    beginner: "Who sits where.",
    engineer: "CarOccupantZoneManager.",
    architect: "User login applies device affinity.",
    compareId: "zone-occupant" },
  { id: "volumegroup", name: "Volume group", cat: "AAOS", layer: "AAOS",
    short: "Devices that share one knob.",
    catch: "Not the same as a context.",
    beginner: "One hotel-room dimmer.",
    engineer: "Same gain curve required inside a group.",
    architect: "Fixed volume → HAL applies the index." },
  { id: "bus", name: "Bus device", cat: "AAOS", layer: "Policy",
    short: "AUDIO_DEVICE_OUT_BUS plus an address string.",
    catch: "Cabin is usually BUS, not SPEAKER.",
    beginner: "A labeled cable.",
    engineer: "Must exist in IModule.getAudioPorts().",
    architect: "A typo is silent fallback, not a compile error." },
  { id: "dynamicmix", name: "Dynamic mix", cat: "AAOS", layer: "Policy",
    short: "Runtime AudioPolicy mix used for AAOS routing.",
    catch: "Forces a usage onto a bus for a user.",
    beginner: "A sticky routing rule installed at boot.",
    engineer: "AudioPolicyMix + user-id affinity.",
    architect: "Off if audioUseDynamicRouting is false." },
  { id: "fade", name: "Fade (AAOS 15)", cat: "Focus", layer: "AAOS",
    short: "VolumeShaper enforcement on focus loss.",
    catch: "Skipped for PAUSES_ON_DUCKABLE_LOSS and SPEECH.",
    beginner: "The system turns the loser down.",
    engineer: "car_audio_fade_configuration.xml.",
    architect: "A 50 ms ramp to 0 can hide a 300 ms buffer tail." },
  { id: "fixedvolume", name: "Fixed volume", cat: "AAOS", layer: "HAL",
    short: "Android sends an index; HAL or amp applies gain.",
    catch: "Flinger track volume stays 1.0.",
    beginner: "The knob talks to the amp, not the mixer.",
    engineer: "useFixedVolume.",
    architect: "HAL no-op means dead knobs." },
  { id: "duck", name: "Duck", cat: "Focus", layer: "AAOS",
    short: "Temporary attenuation of a less-important stream.",
    catch: "Hardware duck needs separate devices.",
    beginner: "Music quieter when nav talks.",
    engineer: "Software VolumeShaper or HAL gain.",
    architect: "Shared bus = one PCM; the DSP cannot split them." },
  { id: "fastmixer", name: "FastMixer", cat: "Latency", layer: "Flinger",
    short: "Low-period PCM mix thread, often beside MixerThread on the same output.",
    catch: "Still a mixer inside Flinger. ALOGE in the loop can cause the glitch.",
    beginner: "A second, impatient cook for a few PCM tracks that cannot wait.",
    engineer: "Typical 2–5 ms class. Late app → mix silence, do not block. NBLOG preferred.",
    architect: "Binder in the loop is fatal. Effects may demote a fast track back to MixerThread.",
    compareId: "mixer-fast" },
  { id: "mixerthread", name: "MixerThread", cat: "Latency", layer: "Flinger",
    short: "Normal / deep-buffer mix thread — the default PCM kitchen.",
    catch: "Larger period than FastMixer. Still the common media path.",
    beginner: "Flinger adds PCM tracks together, then sends one mixed PCM to the HAL.",
    engineer: "threadLoop mix + AIDL Command.burst. Deep-buffer is this thread with a large period.",
    architect: "Work time > period_ms implies XRUNs. MP3 usually becomes PCM and lands here.",
    compareId: "mixer-fast" },
  { id: "period", name: "Period", cat: "Latency", layer: "Kernel",
    short: "Wake / IRQ quantum of the PCM ring.",
    catch: "period_ms = frames / rate × 1000.",
    beginner: "One bucket on the water wheel.",
    engineer: "hw_params period_size.",
    architect: "IRQ rate = 1000 / period_ms.",
    compareId: "buffer-period" },
  { id: "buffer", name: "Buffer", cat: "Latency", layer: "Kernel",
    short: "Jitter tank = period × period count.",
    catch: "Not the same as a period.",
    beginner: "How many buckets before the turbine starves.",
    engineer: "sw_params start_threshold.",
    architect: "Maxing buffer breaks AEC and nav urgency.",
    compareId: "buffer-period" },
  { id: "xrun", name: "XRUN", cat: "Latency", layer: "Kernel",
    short: "ALSA underrun or overrun.",
    catch: "No counter ⇒ probably not an XRUN.",
    beginner: "An empty or overflowing bucket.",
    engineer: "EPIPE, xrunFrames.",
    architect: "RUNNING + zeros is not an XRUN." },
  { id: "standby", name: "Standby", cat: "Latency", layer: "Flinger",
    short: "Two views: PlaybackThread software standby vs StreamDescriptor STANDBY.",
    catch: "Neither is system suspend.",
    beginner: "The platform turned the lights off to save power; the tunnel is still there.",
    engineer: "Flinger standby sends Command.standby; the HAL stream stays open (StreamDescriptor STANDBY). The vendor HAL may release its PCM/graph.",
    architect: "A one-shot can finish before unmute. Do not treat dumpsys standby and StreamDescriptor.STANDBY as one object.",
    compareId: "standby-suspend" },
  { id: "suspend", name: "Suspend", cat: "Latency", layer: "Kernel",
    short: "Whole AP or vehicle sleep.",
    catch: "Different sleeper from audio standby.",
    beginner: "The device went to sleep.",
    engineer: "Driver resume, FW reload, rails.",
    architect: "Vehicle amp ECU may sleep independently.",
    compareId: "standby-suspend" },
  { id: "tinyalsa", name: "TinyALSA", cat: "ALSA", layer: "Kernel",
    short: "Android userspace ALSA library.",
    catch: "Not PulseAudio.",
    beginner: "How Android opens hw:C,D.",
    engineer: "pcm_open / pcm_write.",
    architect: "tinyplay is the HAL-bypass experiment.",
    compareId: "hal-alsa" },
  { id: "alsa", name: "ALSA", cat: "ALSA", layer: "Kernel",
    short: "Linux PCM state machine and mixer ABI.",
    catch: "ASoC sits on top of it.",
    beginner: "The kernel's sound engine.",
    engineer: "pcm states, hw_params, XRUN.",
    architect: "ioctl is the user/kernel boundary.",
    compareId: "alsa-asoc" },
  { id: "soc", name: "SoC", cat: "ALSA", layer: "HW",
    short: "System on Chip: CPU, pins, often a DSP on one die.",
    catch: "The chip, not the driver.",
    beginner: "The main computer chip in the phone or car.",
    engineer: "DAI pins and DMA engines come out of this die.",
    architect: "SoC ≠ ASoC. ASoC is the Linux framework that wires this chip.",
    compareId: "soc-asoc" },
  { id: "asoc", name: "ASoC", cat: "ALSA", layer: "Kernel",
    short: "ALSA System on Chip wiring framework.",
    catch: "On top of ALSA PCM.",
    beginner: "The factory floor plan for this board.",
    engineer: "Machine, platform (DMA), CPU DAI, codec, DAPM.",
    architect: "Android never calls ASoC; TinyALSA opens a PCM ASoC already wired.",
    compareId: "alsa-asoc" },
  { id: "dai", name: "DAI", cat: "ALSA", layer: "Kernel",
    short: "Digital Audio Interface: I2S / TDM / SLIM / SoundWire plus clocks.",
    catch: "Sample cable. Not I2C.",
    beginner: "The serial port that wiggles audio pins.",
    engineer: "set_fmt, TDM slots, clock provider.",
    architect: "Both ends as consumer means no clocks. Not car XML.",
    compareId: "dai-dci" },
  { id: "dci", name: "DCI", cat: "ALSA", layer: "HW",
    short: "Digital Control Interface — typically I2C/SPI to codec/amp registers.",
    catch: "Not the sample cable.",
    beginner: "The quiet bus that sets mute and gain.",
    engineer: "Programs slot maps, mute bits, amp EN. Parallel to the DAI.",
    architect: "If the schematic labels I2S as DCI, treat it as DAI until the datasheet says I2C.",
    compareId: "dai-dci" },
  { id: "pcm", name: "PCM", cat: "ALSA", layer: "Kernel",
    short: "Pulse-code samples, or the ALSA device that carries them. Say which.",
    catch: "Two meanings.",
    beginner: "The raw numbers that become voltage.",
    engineer: "Format + rate + channels, or snd_pcm.",
    architect: "Compressed and offload are not this PCM mix path.",
    compareId: "pcm-dai" },
  { id: "fe", name: "Front-end (FE)", cat: "DSP", layer: "Kernel",
    short: "The PCM Android/TinyALSA opens.",
    catch: "DPCM binds FE to BE at use-case start.",
    beginner: "The loading dock.",
    engineer: "MultiMedia1, Deep-Buffer, …",
    architect: "Wrong BE: Flinger is happy, cabin is silent.",
    compareId: "fe-be" },
  { id: "be", name: "Back-end (BE)", cat: "DSP", layer: "Kernel",
    short: "The DAI toward codec or amp.",
    catch: "Not the same as the FE number.",
    beginner: "The machine the dock is wired to today.",
    engineer: "I2S, TDM, SLIMbus, SoundWire.",
    architect: "Voice may change clock master on a different BE.",
    compareId: "fe-be" },
  { id: "i2s", name: "I2S", cat: "ALSA", layer: "Kernel",
    short: "Typically two-slot serial audio.",
    catch: "Format bits are not “TDM with 2 slots.”",
    beginner: "Left and right on a cable.",
    engineer: "Philips vs left-justified, polarity.",
    architect: "Polarity mismatch shifts channels.",
    compareId: "i2s-tdm" },
  { id: "tdm", name: "TDM", cat: "ALSA", layer: "Kernel",
    short: "Time-division serial audio: N apartments on one FSYNC, not N Android streams.",
    catch: "Slot mask is not car XML. 6ch ≠ TDM-6.",
    beginner: "A revolving door with many apartments. People walk through one at a time.",
    engineer: "Slot count, slot width, sample width, TX/RX mask, FSYNC polarity.",
    architect: "Stereo into 8 slots = two speakers and six zeros unless HAL upmixes. FSYNC invert rotates every speaker.",
    compareId: "i2s-tdm" },
  { id: "dapm", name: "DAPM", cat: "ALSA", layer: "HW",
    short: "ASoC widget power graph.",
    catch: "Volume 80 ≠ mux selected.",
    beginner: "Only complete hoses get water.",
    engineer: "Routes + widgets.",
    architect: "Incomplete path = digital alive, analog off." },
  { id: "acdb", name: "ACDB", cat: "DSP", layer: "HW",
    short: "Qualcomm calibration and graph database.",
    catch: "Not AOSP.",
    beginner: "The recipe book.",
    engineer: "Use-case + rate + channels tuple.",
    architect: "Missing entry → default mute graph.",
    compareId: "framework-dsp" },
  { id: "dsp", name: "DSP", cat: "DSP", layer: "HW",
    short: "Digital Signal Processor — a second computer for audio.",
    catch: "Not AudioFlinger.",
    beginner: "The extra kitchen that mixes, EQs, cancels echo.",
    engineer: "Own clocks and firmware. Qualcomm audio DSP is often ADSP.",
    architect: "Flinger ACTIVE ≠ DSP graph built.",
    compareId: "dsp-dac" },
  { id: "dac", name: "DAC", cat: "DSP", layer: "HW",
    short: "Digital-to-analog converter: numbers become voltage.",
    catch: "After the DAI.",
    beginner: "The last digital stop before the speaker hears analog.",
    engineer: "In a codec, or inside a smart amp.",
    architect: "RUNNING PCM can still be analog mute here.",
    compareId: "dsp-dac" },
  { id: "adsp", name: "ADSP", cat: "DSP", layer: "HW",
    short: "Qualcomm Hexagon audio DSP.",
    catch: "Own power domain; SSR mutes everything.",
    beginner: "Qualcomm’s name for the audio DSP.",
    engineer: "Graphs via GPR/APR. PAL/AGM live on HLOS, not here.",
    architect: "Do not invent module IDs. Ask the BSP." },
  { id: "hlos", name: "HLOS", cat: "DSP", layer: "HAL",
    short: "High-Level OS: the apps processor Linux (Android + HAL + PAL + AGM).",
    catch: "Not the DSP.",
    beginner: "The big computer. The DSP is a different one.",
    engineer: "HLOS→DSP is GPR/IPC, not Binder.",
    architect: "dumpsys will not name PAL sessions." },
  { id: "pal", name: "PAL", cat: "DSP", layer: "HAL",
    short: "Qualcomm Platform Abstraction Layer — use-cases under the vendor HAL.",
    catch: "Only the HAL calls PAL.",
    beginner: "Vendor library: “this is a media use-case.”",
    engineer: "Not AOSP. Apps and Flinger never call it.",
    architect: "Older chips may use mixer_paths instead of PAL.",
    compareId: "pal-agm" },
  { id: "agm", name: "AGM", cat: "DSP", layer: "HAL",
    short: "Audio Graph Manager — builds the DSP graph for a PAL use-case.",
    catch: "PAL calls AGM. Flinger does not.",
    beginner: "The piece that actually wires the DSP kitchen.",
    engineer: "HLOS. Talks to ADSP over GPR. Starts AFE.",
    architect: "Graph-not-built is AGM/DSP, not car XML.",
    compareId: "pal-agm" },
  { id: "afe", name: "AFE", cat: "DSP", layer: "HW",
    short: "DSP audio front end toward the DAI/codec.",
    catch: "IDs are vendor-specific.",
    beginner: "The DSP’s doorway to the pins.",
    engineer: "Port start after graph build.",
    architect: "Wrong port = wrong speakers. Not TinyALSA pcm_open." },
  { id: "audiocontrol", name: "AudioControl", cat: "AAOS", layer: "HAL",
    short: "AAOS HAL for focus and gain hooks.",
    catch: "Does not play PCM.",
    beginner: "The car sidecar.",
    engineer: "IFocusListener, duck callbacks.",
    architect: "Safety audio must play even if focus is denied.",
    compareId: "core-audiocontrol" },
  { id: "audioserver", name: "audioserver", cat: "API", layer: "Flinger",
    short: "Process hosting Flinger and Policy.",
    catch: "Split from mediaserver around Android 7.",
    beginner: "The audio OS service.",
    engineer: "DEAD_OBJECT means it died.",
    architect: "init restarts it; apps must recreate tracks." },
  { id: "session", name: "Session", cat: "API", layer: "App",
    short: "Groups a track with its effects.",
    catch: "Not the UID.",
    beginner: "A ticket number to join logs.",
    engineer: "getAudioSessionId.",
    architect: "Join app to Flinger with session and uid." },
  { id: "patch", name: "Patch", cat: "API", layer: "Policy",
    short: "Live Policy connection between ports.",
    catch: "Possible topology is not a live patch.",
    beginner: "Who is cabled to whom right now.",
    engineer: "setAudioPatch / dumpsys patches.",
    architect: "Mix exists but patch still on speaker = bug." },
  { id: "hwparams", name: "hw_params", cat: "ALSA", layer: "Kernel",
    short: "ALSA hardware contract.",
    catch: "Includes periods, not just rate.",
    beginner: "What the wheel will accept.",
    engineer: "rate, format, channels, period.",
    architect: "EINVAL = profile lie or unsupported period." },
  { id: "deepbuffer", name: "Deep buffer", cat: "Latency", layer: "Flinger",
    short: "Large-period output for media and power.",
    catch: "Bad for the first nav word.",
    beginner: "A big tank, few wakeups.",
    engineer: "AUDIO_OUTPUT_FLAG_DEEP_BUFFER.",
    architect: "Do not put chimes here." },
  { id: "direct", name: "DirectOutputThread", cat: "HAL", layer: "Flinger",
    short: "Flinger PlaybackThread with no software mix — one track owns the output.",
    catch: "Does not bypass AudioFlinger. Skips the mixer.",
    beginner: "One train. Policy still booked it. Flinger still drives it. Nobody else may board.",
    engineer: "Exclusive PCM or compressed passthrough (HDMI AC3). AUDIO_OUTPUT_FLAG_DIRECT.",
    architect: "Nav needs another output/bus. You cannot mix into a bitstream or an exclusive PCM.",
    compareId: "pcm-path" },
  { id: "mmap", name: "MMAP", cat: "Latency", layer: "HAL",
    short: "Shared-memory low-latency path.",
    catch: "Still Policy plus Flinger.",
    beginner: "Skip the extra copy.",
    engineer: "AAudio exclusive if the HAL supports it.",
    architect: "burst value 0; samples live in mmap." },
  { id: "aaudio", name: "AAudio", cat: "API", layer: "App",
    short: "NDK low-latency API.",
    catch: "Not a second OS.",
    beginner: "The modern native tap.",
    engineer: "MMAP or mixer path.",
    architect: "Routing still goes through Policy." },
  { id: "mixerpaths", name: "mixer_paths.xml", cat: "DSP", layer: "HW",
    short: "Vendor kcontrol sequences (often Qualcomm).",
    catch: "Not audio_policy_configuration.xml.",
    beginner: "Which analog switches flip for a use case.",
    engineer: "Path apply on start.",
    architect: "Policy does not parse this file.",
    compareId: "framework-dsp" },
  { id: "ssr", name: "SSR", cat: "DSP", layer: "HW",
    short: "ADSP subsystem restart.",
    catch: "Global audio outage.",
    beginner: "The kitchen rebooted.",
    engineer: "All graphs gone.",
    architect: "Do not debug a single app." },
  { id: "carmedia", name: "CarMediaService", cat: "AAOS", layer: "AAOS",
    short: "Which source is active and whether it is started.",
    catch: "Needs SharedPreferences after user unlock.",
    beginner: "The car's source-knob software.",
    engineer: "mPendingInit, MediaConnection.",
    architect: "Focus OK + no play = user init race." },
  { id: "mediafocuscontrol", name: "MediaFocusControl", cat: "Focus", layer: "App",
    short: "Java focus plus player mute/fade enforcement.",
    catch: "Can mute losers that ignore LOSS.",
    beginner: "The usher who can cover the mic.",
    engineer: "Lives in system_server.",
    architect: "Assistant-ignore-LOSS workaround belongs here, not in the HAL." },
  { id: "offload", name: "OffloadThread", cat: "HAL", layer: "Flinger",
    short: "Flinger PlaybackThread that ships compressed frames to the DSP to decode.",
    catch: "Still AudioFlinger. Not a PCM mixer. Not the default MP3 path.",
    beginner: "The post office: Flinger sends the zip file, the DSP unpacks it.",
    engineer: "AUDIO_OUTPUT_FLAG_COMPRESS_OFFLOAD. Pause/flush/XRUN ≠ MixerThread.",
    architect: "Nav cannot join. Need a separate MixerThread / bus. Offload is advertised by HAL+Policy, not by the file extension.",
    compareId: "pcm-path" },
  { id: "hal", name: "Audio HAL", cat: "HAL", layer: "HAL",
    short: "Vendor contract between Flinger/Policy and drivers.",
    catch: "Classify AIDL vs HIDL before naming methods.",
    beginner: "The customs border.",
    engineer: "IModule on Android 15.",
    architect: "libaudiohal hides IPC; bugs still live in the vendor service.",
    compareId: "hal-alsa" },
  { id: "contenttype", name: "Content type", cat: "Focus", layer: "App",
    short: "What the payload is (speech, music, movie, sonification).",
    catch: "Rarely selects the bus by itself.",
    beginner: "Speech vs music.",
    engineer: "CONTENT_TYPE_*.",
    architect: "SPEECH is often unfadeable." },
  { id: "samplerate", name: "Sample rate", cat: "PCM", layer: "Kernel",
    short: "Frames per second of the stream clock (Hz).",
    catch: "Not the same as IRQ rate.",
    beginner: "How often a full multi-channel snapshot is taken.",
    engineer: "48000 means 48,000 frames/s, not 48,000 left samples if stereo.",
    architect: "Policy profile, HAL, and hw_params must agree or open fails.",
    compareId: "sample-frame" },
  { id: "sample", name: "Sample", cat: "PCM", layer: "Kernel",
    short: "One channel's amplitude at one instant.",
    catch: "Not a frame.",
    beginner: "One number for one speaker at one tick.",
    engineer: "Width is bit depth (16/24/32).",
    architect: "Bytes/sample is packing, not just 'bit depth' (S24_3LE vs S24_LE).",
    compareId: "sample-frame" },
  { id: "frame", name: "Frame", cat: "PCM", layer: "Kernel",
    short: "One instant across every channel in the stream.",
    catch: "Stereo frame = L + R, not one sample.",
    beginner: "A snapshot of all speakers at the same moment.",
    engineer: "frame_size = channels × bytes/sample.",
    architect: "ALSA period_size is in frames, not bytes.",
    compareId: "sample-frame" },
  { id: "framerate", name: "Frame rate", cat: "PCM", layer: "Kernel",
    short: "Same number as sample rate for PCM: frames per second.",
    catch: "People say sample rate; ALSA counts frames.",
    beginner: "How many snapshots per second.",
    engineer: "period_ms = period_frames / rate × 1000.",
    architect: "Do not mix this up with display refresh or encoded bit-rate." },
  { id: "framesize", name: "Frame size", cat: "PCM", layer: "Kernel",
    short: "Bytes in one frame = channels × bytes per sample.",
    catch: "24-bit packed is 3 bytes, 24-in-32 is 4.",
    beginner: "How fat each snapshot is on the wire.",
    engineer: "bytes/period = frames/period × frame_size.",
    architect: "Wrong frame size looks like 'half speed' or channel swap.",
    compareId: "bit-depth" },
  { id: "channels", name: "Channels", cat: "PCM", layer: "Kernel",
    short: "How many samples live in one PCM frame — a group photo, same instant.",
    catch: "6 channels is 5.1. It is not “6 TDM slots.”",
    beginner: "1 = mono, 2 = stereo, 6 = 5.1 (FL FR C LFE RL RR).",
    engineer: "Channel mask names the people. Slot mask names the apartments on the wire.",
    architect: "Count match with TDM still can hit the wrong speaker. DAI map ≠ car XML.",
    compareId: "channel-slot" },
  { id: "periodcount", name: "Period count", cat: "PCM", layer: "Kernel",
    short: "How many periods make the ring buffer.",
    catch: "Buffer = period × count. Not the period itself.",
    beginner: "How many buckets on the wheel.",
    engineer: "Typical 2–8. start_threshold is often in periods.",
    architect: "Count 2 is twitchy; huge count hides XRUNs and kills AEC.",
    compareId: "buffer-period" },
  { id: "bitdepth", name: "Bit depth", cat: "PCM", layer: "Kernel",
    short: "Amplitude resolution of one sample.",
    catch: "Container width can be larger than useful bits.",
    beginner: "How fine the volume ladder is.",
    engineer: "S16_LE, S24_LE, S24_3LE, S32_LE.",
    architect: "24-in-32 is not 32-bit SNR. Ask the codec which packing.",
    compareId: "bit-depth" },
  { id: "s16", name: "16-bit PCM (S16_LE)", cat: "PCM", layer: "Kernel",
    short: "Signed 16-bit little-endian; 2 bytes per sample.",
    catch: "Still the mixer default on many products.",
    beginner: "CD-style numbers.",
    engineer: "frame_size stereo = 4 bytes.",
    architect: "Dither/volume in 16-bit is noisier than 24-bit at the DAC.",
    compareId: "bit-depth" },
  { id: "s24", name: "24-bit PCM", cat: "PCM", layer: "Kernel",
    short: "24 useful bits; packing is either 3 bytes or 4.",
    catch: "S24_LE ≠ S24_3LE.",
    beginner: "Finer steps than 16-bit.",
    engineer: "S24_3LE = packed 3 bytes; S24_LE often 24 bits in 32.",
    architect: "Mismatch here is EINVAL or channel crawl, not 'quiet audio'.",
    compareId: "bit-depth" },
  { id: "s32", name: "32-bit PCM (S32_LE)", cat: "PCM", layer: "Kernel",
    short: "4 bytes per sample; may be 32-bit or 24-in-32.",
    catch: "Width is not automatically 32-bit SNR.",
    beginner: "The fattest common integer sample.",
    engineer: "Confirm Q format with the codec datasheet.",
    architect: "Flinger mixer may convert; the HAL must still open the real format.",
    compareId: "bit-depth" },
  { id: "interleaved", name: "Interleaved", cat: "PCM", layer: "Kernel",
    short: "L R L R … in one buffer, not planar LLL then RRR.",
    catch: "Android PCM playback is interleaved.",
    beginner: "Left and right take turns in the same list.",
    engineer: "Non-interleaved is a different API/layout.",
    architect: "TDM slot maps sit on top of this packing." },
  { id: "linearpcm", name: "Linear PCM", cat: "PCM", layer: "Flinger",
    short: "Uncompressed samples mixed in AudioFlinger.",
    catch: "Not a compressed bitstream and not DSP-offload decode.",
    beginner: "The raw numbers the mixer adds together.",
    engineer: "MixerThread / FastMixer paths.",
    architect: "If two PCM streams share one bus, the DSP sees one mixed PCM.",
    compareId: "pcm-path" },
  { id: "compressed", name: "Compressed audio", cat: "PCM", layer: "HAL",
    short: "Encoded frames (AAC, AC3, FLAC…) not mixer samples.",
    catch: "You cannot mix nav into an AC3 HDMI stream in Flinger.",
    beginner: "A zip file of sound, not the sound itself.",
    engineer: "Passthrough vs decode-in-framework vs offload.",
    architect: "DIRECT + compressed often means no software mix.",
    compareId: "pcm-path" },
];

export const TERM_CATS = ["All", "PCM", "API", "HAL", "AAOS", "DSP", "ALSA", "Focus", "Latency"];

export function getTerm(id) {
  return TERMS.find((t) => t.id === id) || null;
}
