#!/usr/bin/env node
/**
 * Resolve every source reference in portal/content/** against the pinned AOSP tag.
 *
 *   npm run sources            fetch (cached in .cache/aosp), resolve symbol → line,
 *                              write content/sources.lock.json + content/sources/excerpts.json
 *   npm run sources -- --check re-fetch from googlesource and fail if any locked line,
 *                              file hash or excerpt no longer matches (network; for CI)
 *
 * A reference is `{ repo, path, symbol?, occurrence?, before?, after?, highlight? }`.
 * The symbol is matched as a literal substring; `occurrence` picks the n-th match.
 * Kernel paths (kernel/common, a moving branch) are only checked for existence.
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { AOSP_TAG, KERNEL_BRANCH, aospRawUrl, isKernel } from "../src/lib/aosp.js";
import { portal, loadContent, collectSourceRefs, refKey, LOCK_FILE, EXCERPTS_FILE, readJson } from "./content-lib.mjs";

const CHECK = process.argv.includes("--check");
const REFRESH = process.argv.includes("--refresh") || CHECK;
const cacheDir = path.join(portal, ".cache", "aosp", AOSP_TAG);
const MAX_EXCERPT = 30;

const sha256 = (s) => crypto.createHash("sha256").update(s).digest("hex");

async function fetchFile(ref) {
  const cache = path.join(cacheDir, ref.repo, ref.path);
  if (!REFRESH && fs.existsSync(cache)) return fs.readFileSync(cache, "utf8");
  const url = aospRawUrl(ref);
  for (let attempt = 1; ; attempt++) {
    const res = await fetch(url);
    if (res.ok) {
      const text = Buffer.from(await res.text(), "base64").toString("utf8");
      fs.mkdirSync(path.dirname(cache), { recursive: true });
      fs.writeFileSync(cache, text);
      return text;
    }
    if (res.status === 404) throw new Error(`404 ${ref.repo}/${ref.path} at ${isKernel(ref.repo) ? KERNEL_BRANCH : AOSP_TAG}`);
    if (attempt >= 4) throw new Error(`HTTP ${res.status} for ${url}`);
    await new Promise((r) => setTimeout(r, 1000 * attempt));
  }
}

function resolve(ref, text) {
  const lines = text.split("\n");
  const want = ref.occurrence || 1;
  let seen = 0;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes(ref.symbol) && ++seen === want) {
      const before = ref.before ?? 2;
      const after = Math.min(ref.after ?? 10, MAX_EXCERPT - 1 - before);
      const start = Math.max(1, i + 1 - before);
      const end = Math.min(lines.length, i + 1 + after);
      return { line: i + 1, start, end, excerpt: lines.slice(start - 1, end) };
    }
  }
  throw new Error(`symbol not found (occurrence ${want}): "${ref.symbol}" in ${ref.repo}/${ref.path}`);
}

const content = loadContent();
const refs = collectSourceRefs(content);
const unique = new Map();
for (const { ref, where } of refs) if (!unique.has(refKey(ref))) unique.set(refKey(ref), { ref, where });

const oldLock = readJson(LOCK_FILE, { sources: {} });
const oldEx = readJson(EXCERPTS_FILE, {});
const lock = { tag: AOSP_TAG, kernelBranch: KERNEL_BRANCH, note: "Generated by scripts/fetch-sources.mjs. Do not edit by hand.", sources: {} };
const excerpts = {};
const problems = [];
const files = new Map();

for (const [key, { ref, where }] of [...unique.entries()].sort()) {
  try {
    const fk = `${ref.repo}/${ref.path}`;
    if (!files.has(fk)) files.set(fk, await fetchFile(ref));
    const text = files.get(fk);
    const entry = { repo: ref.repo, path: ref.path, ref: isKernel(ref.repo) ? `heads/${KERNEL_BRANCH}` : `tags/${AOSP_TAG}` };
    if (!isKernel(ref.repo)) entry.fileSha256 = sha256(text);
    if (ref.symbol) {
      const r = resolve(ref, text);
      Object.assign(entry, { symbol: ref.symbol, occurrence: ref.occurrence || 1, line: r.line, start: r.start, end: r.end, excerptSha256: sha256(r.excerpt.join("\n")) });
      excerpts[key] = { start: r.start, lines: r.excerpt };
    }
    if (CHECK) {
      const old = oldLock.sources[key];
      if (!old) problems.push(`not in lock: ${key} (${where})`);
      else if (!isKernel(ref.repo)) {
        for (const f of ["fileSha256", "line", "excerptSha256"]) if (old[f] !== entry[f]) problems.push(`${key}: ${f} ${old[f]} → ${entry[f]}`);
      }
    }
    lock.sources[key] = entry;
  } catch (e) {
    problems.push(`${e.message}  (${where})`);
  }
}

if (CHECK) {
  if (problems.length) {
    console.error(`sources --check: ${problems.length} problem(s)\n  ${problems.join("\n  ")}`);
    process.exit(1);
  }
  console.log(`sources --check: ${unique.size} references still match ${AOSP_TAG}`);
  process.exit(0);
}
if (problems.length) {
  console.error(`fetch-sources: ${problems.length} problem(s)\n  ${problems.join("\n  ")}`);
  process.exit(1);
}
const moved = Object.keys(lock.sources).filter((k) => oldLock.sources[k] && oldLock.sources[k].line !== lock.sources[k].line);
fs.mkdirSync(path.dirname(EXCERPTS_FILE), { recursive: true });
fs.writeFileSync(LOCK_FILE, JSON.stringify(lock, null, 2) + "\n");
fs.writeFileSync(EXCERPTS_FILE, JSON.stringify(excerpts, null, 1) + "\n");
console.log(`fetch-sources: ${unique.size} references at ${AOSP_TAG} (${files.size} files)${moved.length ? `; lines moved: ${moved.join(", ")}` : ""}`);
void oldEx;
